{{- if and .Values.enabled (eq .Values.deployType "Deployment") -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rayservice.fullname" . }}
  labels:
    {{- include "rayservice.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ if .Values.rollout.enabled }}{{ 0 }}{{ else }}{{ .Values.replicas }}{{ end }}
  {{- end }}
  strategy:
    type: {{ .Values.strategy | quote }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  selector:
    matchLabels:
      {{- include "rayservice.selectorLabels" . | nindent 6 }}
  template: {{ include "rayservice.template.pod" . | nindent 4 }}
{{ end }}