{{- if and .Values.enabled (eq .Values.deployType "RayService") -}}
---
apiVersion: ray.io/v1
kind: RayService
metadata:
  name: {{ include "rayservice.fullname" . }}
spec:
  serveConfigV2: {{ include "rayservice.serveConfigV2" . }}
  rayClusterConfig: 
    {{ include "rayservice.rayClusterConfig" . }}
{{ end }}