{{- $sa := .Values.serviceAccount -}}
{{- if and .Values.enabled (and (or $sa.create .Values.vault.enabled) (not $sa.existingServiceAccount)) -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rayservice.serviceAccountName" . }}
  labels:
    {{- include "rayservice.labels" . | nindent 4 }}
  {{- with $sa.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ $sa.automountServiceAccountToken }}
{{ end }}
